{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyM4cKan8OW+kcv0rkRYqjUr",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/Habibaaboalhassan66/swimming-detection/blob/main/strokedetection.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "!pip install tensorflow opencv-python-headless numpy tqdm matplotlib -q"
      ],
      "metadata": {
        "id": "Hk7Eqd_t2cHa"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "!pip install numpy==2.0.2 -q --force-reinstall"
      ],
      "metadata": {
        "id": "FqMiYwxq2x84"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "import tensorflow as tf\n",
        "import numpy as np\n",
        "print(f\"TensorFlow: {tf.__version__}\")\n",
        "print(f\"NumPy: {np.__version__}\")\n",
        "print(\"✅ Ready\")"
      ],
      "metadata": {
        "id": "OVcV6aFI28Iu"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "from google.colab import drive\n",
        "drive.mount(\"/content/drive\")"
      ],
      "metadata": {
        "id": "WyxJPaxb3Doi"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "markdown",
      "source": [
        "When we use MobileNetV2(only for comparison)"
      ],
      "metadata": {
        "id": "SQYHe_pf65ev"
      }
    },
    {
      "cell_type": "code",
      "source": [
        "# @title\n",
        "\"\"\"\n",
        "stroke_detection_cnn.py\n",
        "────────────────────────\n",
        "FILE 1 of 4 — Stroke Detection CNN\n",
        "\n",
        "PURPOSE:\n",
        "  Trains a CNN to classify swimming stroke type (breaststroke vs butterfly)\n",
        "  from video frames, then uses the trained model to auto-detect the stroke\n",
        "  in new test videos.\n",
        "\n",
        "PIPELINE POSITION:\n",
        "  New video → [THIS FILE: detect stroke] → pose estimation → injury detection\n",
        "\n",
        "HOW TO USE IN COLAB:\n",
        "  Cell 1 — install:\n",
        "    !pip install tensorflow opencv-python-headless numpy tqdm matplotlib -q\n",
        "\n",
        "  Cell 2 — mount drive:\n",
        "    from google.colab import drive\n",
        "    drive.mount(\"/content/drive\")\n",
        "\n",
        "  Cell 3 — paste and run this file\n",
        "\n",
        "WHAT CHANGES FROM DEFAULT:\n",
        "  - TRAIN_FOLDERS: paths to your processed_frames_v4 folders\n",
        "  - TEST_FOLDERS:  paths to your test video folders\n",
        "  - MODEL_SAVE_PATH: where to save the trained CNN\n",
        "  - IMG_SIZE: resize frames to this before feeding CNN (default 224x224)\n",
        "  - EPOCHS: training epochs (default 20)\n",
        "  - BATCH_SIZE: batch size (default 32)\n",
        "\"\"\"\n",
        "\n",
        "# ══════════════════════════════════════════════\n",
        "#  ① CONFIG\n",
        "# ══════════════════════════════════════════════\n",
        "import os\n",
        "os.environ[\"TF_CPP_MIN_LOG_LEVEL\"] = \"2\"  # suppress TF warnings\n",
        "\n",
        "# Training data — your processed frames organized by stroke\n",
        "TRAIN_BASE_OLD = \"/content/drive/MyDrive/GP26-Habiba-LearningWhatMatters/Dataset/Video/processed_frames_v4/old\"\n",
        "TRAIN_BASE_NEW = \"/content/drive/MyDrive/GP26-Habiba-LearningWhatMatters/Dataset/Video/processed_frames_v4/new\"\n",
        "\n",
        "# Test folders — new videos to predict stroke on\n",
        "TEST_FOLDERS = {\n",
        "    \"breaststroke\": \"/content/drive/MyDrive/GP26-Habiba-LearningWhatMatters/Dataset/Video/Front view/test/breaststroke\",\n",
        "    \"butterfly\":    \"/content/drive/MyDrive/GP26-Habiba-LearningWhatMatters/Dataset/Video/Front view/test/butterfly\",\n",
        "}\n",
        "\n",
        "# Where to save the trained model\n",
        "MODEL_SAVE_PATH = \"/content/drive/MyDrive/GP26-Habiba-LearningWhatMatters/Models/stroke_detection_cnn.h5\"\n",
        "\n",
        "# CNN settings\n",
        "IMG_SIZE   = 224    # resize frames to IMG_SIZE x IMG_SIZE\n",
        "BATCH_SIZE = 32\n",
        "EPOCHS     = 20\n",
        "VAL_SPLIT  = 0.2    # 20% of training data used for validation\n",
        "\n",
        "# Stroke labels\n",
        "STROKE_LABELS = {\n",
        "    \"breaststroke\": 0,\n",
        "    \"butterfly\":    1,\n",
        "}\n",
        "LABEL_TO_STROKE = {v: k for k, v in STROKE_LABELS.items()}\n",
        "\n",
        "# ══════════════════════════════════════════════\n",
        "#  ② IMPORTS\n",
        "# ══════════════════════════════════════════════\n",
        "import cv2\n",
        "import numpy as np\n",
        "import tensorflow as tf\n",
        "from tensorflow import keras\n",
        "from tensorflow.keras import layers\n",
        "from pathlib import Path\n",
        "from tqdm import tqdm\n",
        "import matplotlib.pyplot as plt\n",
        "from datetime import datetime\n",
        "import json\n",
        "\n",
        "print(f\"TensorFlow version: {tf.__version__}\")\n",
        "print(f\"GPU available: {len(tf.config.list_physical_devices('GPU')) > 0}\")\n",
        "\n",
        "# ══════════════════════════════════════════════\n",
        "#  ③ DATA LOADING\n",
        "# ══════════════════════════════════════════════\n",
        "def identify_stroke_from_path(folder_name: str) -> str:\n",
        "    \"\"\"\n",
        "    Identify stroke type from folder name.\n",
        "    Handles names like:\n",
        "      breaststroke_front_S01 → breaststroke\n",
        "      butterfly_front_S05   → butterfly\n",
        "      freestyle_front_S01   → freestyle (excluded)\n",
        "    \"\"\"\n",
        "    folder_lower = folder_name.lower()\n",
        "    if \"breaststroke\" in folder_lower:\n",
        "        return \"breaststroke\"\n",
        "    elif \"butterfly\" in folder_lower:\n",
        "        return \"butterfly\"\n",
        "    else:\n",
        "        return None  # exclude freestyle and unknown\n",
        "\n",
        "\n",
        "def load_frame(image_path: str, img_size: int) -> np.ndarray:\n",
        "    \"\"\"Load and preprocess a single frame for CNN input.\"\"\"\n",
        "    img = cv2.imread(image_path)\n",
        "    if img is None:\n",
        "        return None\n",
        "    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)\n",
        "    img = cv2.resize(img, (img_size, img_size))\n",
        "    img = img.astype(np.float32) / 255.0  # normalize to [0, 1]\n",
        "    return img\n",
        "\n",
        "\n",
        "def load_dataset(base_paths: list, img_size: int,\n",
        "                 max_per_class: int = 1000) -> tuple:\n",
        "    \"\"\"\n",
        "    Load frames from all stroke subfolders.\n",
        "    Returns (images, labels, class_counts).\n",
        "\n",
        "    max_per_class: limit frames per stroke to balance dataset\n",
        "    \"\"\"\n",
        "    images = []\n",
        "    labels = []\n",
        "    class_counts = {\"breaststroke\": 0, \"butterfly\": 0}\n",
        "\n",
        "    print(\"\\n📂 Loading training dataset...\")\n",
        "\n",
        "    for base_path in base_paths:\n",
        "        base = Path(base_path)\n",
        "        if not base.exists():\n",
        "            print(f\"  ⚠️  Not found: {base_path}\")\n",
        "            continue\n",
        "\n",
        "        # Each subfolder is a video (e.g. breaststroke_front_S01)\n",
        "        for video_folder in sorted(base.iterdir()):\n",
        "            if not video_folder.is_dir():\n",
        "                continue\n",
        "\n",
        "            stroke = identify_stroke_from_path(video_folder.name)\n",
        "            if stroke is None:\n",
        "                continue  # skip freestyle\n",
        "\n",
        "            label = STROKE_LABELS[stroke]\n",
        "\n",
        "            # Get frames from this video\n",
        "            frames = sorted(video_folder.glob(\"*.jpg\"))\n",
        "            if not frames:\n",
        "                continue\n",
        "\n",
        "            # Sample evenly to avoid too many frames from one video\n",
        "            max_from_video = min(50, len(frames))\n",
        "            step  = max(1, len(frames) // max_from_video)\n",
        "            sampled = frames[::step][:max_from_video]\n",
        "\n",
        "            loaded = 0\n",
        "            for frame_path in sampled:\n",
        "                # Check class limit\n",
        "                if class_counts[stroke] >= max_per_class:\n",
        "                    break\n",
        "                img = load_frame(str(frame_path), img_size)\n",
        "                if img is not None:\n",
        "                    images.append(img)\n",
        "                    labels.append(label)\n",
        "                    class_counts[stroke] += 1\n",
        "                    loaded += 1\n",
        "\n",
        "            print(f\"  [{stroke}] {video_folder.name}: {loaded} frames loaded\")\n",
        "\n",
        "    print(f\"\\n  Total frames loaded:\")\n",
        "    for stroke, count in class_counts.items():\n",
        "        print(f\"    {stroke}: {count} frames\")\n",
        "\n",
        "    return np.array(images), np.array(labels), class_counts\n",
        "\n",
        "\n",
        "# ══════════════════════════════════════════════\n",
        "#  ④ CNN MODEL ARCHITECTURE\n",
        "# ══════════════════════════════════════════════\n",
        "def build_stroke_cnn(img_size: int, num_classes: int = 2) -> keras.Model:\n",
        "    \"\"\"\n",
        "    Build CNN for stroke classification.\n",
        "\n",
        "    Architecture:\n",
        "      - MobileNetV2 base (pre-trained on ImageNet) → transfer learning\n",
        "      - Global Average Pooling\n",
        "      - Dense 256 → Dropout → Dense 128 → Dropout\n",
        "      - Output: 2 classes (breaststroke / butterfly)\n",
        "\n",
        "    WHY MobileNetV2:\n",
        "      - Lightweight → runs on Colab CPU/GPU\n",
        "      - Pre-trained on ImageNet → already knows visual features\n",
        "      - Fine-tuned on your frames → learns stroke-specific patterns\n",
        "      - Same fine-tuning principle as your Roboflow model\n",
        "    \"\"\"\n",
        "    # Base model — pre-trained MobileNetV2\n",
        "    base_model = keras.applications.MobileNetV2(\n",
        "        input_shape=(img_size, img_size, 3),\n",
        "        include_top=False,\n",
        "        weights=\"imagenet\"\n",
        "    )\n",
        "\n",
        "    # Freeze base model initially\n",
        "    base_model.trainable = False\n",
        "\n",
        "    # Build full model\n",
        "    inputs = keras.Input(shape=(img_size, img_size, 3))\n",
        "    x = keras.applications.mobilenet_v2.preprocess_input(inputs)\n",
        "    x = base_model(x, training=False)\n",
        "    x = layers.GlobalAveragePooling2D()(x)\n",
        "    x = layers.Dense(256, activation=\"relu\")(x)\n",
        "    x = layers.Dropout(0.3)(x)\n",
        "    x = layers.Dense(128, activation=\"relu\")(x)\n",
        "    x = layers.Dropout(0.3)(x)\n",
        "\n",
        "    if num_classes == 2:\n",
        "        outputs = layers.Dense(1, activation=\"sigmoid\")(x)\n",
        "    else:\n",
        "        outputs = layers.Dense(num_classes, activation=\"softmax\")(x)\n",
        "\n",
        "    model = keras.Model(inputs, outputs)\n",
        "\n",
        "    return model, base_model\n",
        "\n",
        "\n",
        "def compile_model(model: keras.Model, num_classes: int = 2) -> keras.Model:\n",
        "    \"\"\"Compile the CNN model.\"\"\"\n",
        "    if num_classes == 2:\n",
        "        model.compile(\n",
        "            optimizer=keras.optimizers.Adam(learning_rate=1e-3),\n",
        "            loss=\"binary_crossentropy\",\n",
        "            metrics=[\"accuracy\"]\n",
        "        )\n",
        "    else:\n",
        "        model.compile(\n",
        "            optimizer=keras.optimizers.Adam(learning_rate=1e-3),\n",
        "            loss=\"sparse_categorical_crossentropy\",\n",
        "            metrics=[\"accuracy\"]\n",
        "        )\n",
        "    return model\n",
        "\n",
        "\n",
        "# ══════════════════════════════════════════════\n",
        "#  ⑤ TRAINING\n",
        "# ══════════════════════════════════════════════\n",
        "def train_stroke_cnn(images: np.ndarray, labels: np.ndarray) -> tuple:\n",
        "    \"\"\"\n",
        "    Train the stroke detection CNN in two phases:\n",
        "\n",
        "    Phase 1 — Train only the top layers (base frozen)\n",
        "      → Quick learning of stroke-specific features\n",
        "\n",
        "    Phase 2 — Fine-tune the top layers of base model too\n",
        "      → Refine low-level features for swimming context\n",
        "\n",
        "    Returns (model, history)\n",
        "    \"\"\"\n",
        "    print(\"\\n🧠 Building CNN model...\")\n",
        "    model, base_model = build_stroke_cnn(IMG_SIZE)\n",
        "    model = compile_model(model)\n",
        "    model.summary()\n",
        "\n",
        "    # Shuffle data\n",
        "    idx     = np.random.permutation(len(images))\n",
        "    images  = images[idx]\n",
        "    labels  = labels[idx]\n",
        "\n",
        "    # Split train/val\n",
        "    val_size   = int(len(images) * VAL_SPLIT)\n",
        "    x_train, x_val = images[val_size:], images[:val_size]\n",
        "    y_train, y_val = labels[val_size:], labels[:val_size]\n",
        "\n",
        "    print(f\"\\n  Training: {len(x_train)} frames\")\n",
        "    print(f\"  Validation: {len(x_val)} frames\")\n",
        "\n",
        "    # Callbacks\n",
        "    callbacks = [\n",
        "        keras.callbacks.EarlyStopping(\n",
        "            patience=5,\n",
        "            restore_best_weights=True,\n",
        "            monitor=\"val_accuracy\"\n",
        "        ),\n",
        "        keras.callbacks.ReduceLROnPlateau(\n",
        "            factor=0.5,\n",
        "            patience=3,\n",
        "            monitor=\"val_loss\"\n",
        "        ),\n",
        "    ]\n",
        "\n",
        "    # ── Phase 1: Train top layers only ──────────\n",
        "    print(\"\\n📈 Phase 1 — Training top layers (base frozen)...\")\n",
        "    history1 = model.fit(\n",
        "        x_train, y_train,\n",
        "        validation_data=(x_val, y_val),\n",
        "        epochs=EPOCHS,\n",
        "        batch_size=BATCH_SIZE,\n",
        "        callbacks=callbacks,\n",
        "        verbose=1\n",
        "    )\n",
        "\n",
        "    # ── Phase 2: Fine-tune top layers of base ───\n",
        "    print(\"\\n📈 Phase 2 — Fine-tuning (unfreezing top 30 layers)...\")\n",
        "    base_model.trainable = True\n",
        "\n",
        "    # Only unfreeze top 30 layers\n",
        "    for layer in base_model.layers[:-30]:\n",
        "        layer.trainable = False\n",
        "\n",
        "    # Recompile with lower learning rate\n",
        "    model.compile(\n",
        "        optimizer=keras.optimizers.Adam(learning_rate=1e-5),\n",
        "        loss=\"binary_crossentropy\",\n",
        "        metrics=[\"accuracy\"]\n",
        "    )\n",
        "\n",
        "    history2 = model.fit(\n",
        "        x_train, y_train,\n",
        "        validation_data=(x_val, y_val),\n",
        "        epochs=10,\n",
        "        batch_size=BATCH_SIZE,\n",
        "        callbacks=callbacks,\n",
        "        verbose=1\n",
        "    )\n",
        "\n",
        "    return model, history1, history2, x_val, y_val\n",
        "\n",
        "\n",
        "# ══════════════════════════════════════════════\n",
        "#  ⑥ EVALUATION\n",
        "# ══════════════════════════════════════════════\n",
        "def evaluate_model(model: keras.Model,\n",
        "                   x_val: np.ndarray,\n",
        "                   y_val: np.ndarray) -> dict:\n",
        "    \"\"\"Evaluate model on validation set.\"\"\"\n",
        "    print(\"\\n📊 Evaluating model...\")\n",
        "\n",
        "    loss, accuracy = model.evaluate(x_val, y_val, verbose=0)\n",
        "\n",
        "    # Get predictions\n",
        "    preds = model.predict(x_val, verbose=0)\n",
        "    pred_labels = (preds > 0.5).astype(int).flatten()\n",
        "\n",
        "    # Per-class accuracy\n",
        "    for stroke, label_id in STROKE_LABELS.items():\n",
        "        mask     = y_val == label_id\n",
        "        if mask.sum() > 0:\n",
        "            correct  = (pred_labels[mask] == y_val[mask]).sum()\n",
        "            acc      = correct / mask.sum() * 100\n",
        "            print(f\"  {stroke}: {correct}/{mask.sum()} correct ({acc:.1f}%)\")\n",
        "\n",
        "    print(f\"\\n  Overall accuracy: {accuracy*100:.1f}%\")\n",
        "    print(f\"  Loss: {loss:.4f}\")\n",
        "\n",
        "    return {\"accuracy\": accuracy, \"loss\": loss}\n",
        "\n",
        "\n",
        "def plot_training_history(history1, history2) -> None:\n",
        "    \"\"\"Plot training curves.\"\"\"\n",
        "    fig, axes = plt.subplots(1, 2, figsize=(12, 4))\n",
        "\n",
        "    # Combine histories\n",
        "    acc     = history1.history[\"accuracy\"]     + history2.history[\"accuracy\"]\n",
        "    val_acc = history1.history[\"val_accuracy\"] + history2.history[\"val_accuracy\"]\n",
        "    loss    = history1.history[\"loss\"]         + history2.history[\"loss\"]\n",
        "    val_loss= history1.history[\"val_loss\"]     + history2.history[\"val_loss\"]\n",
        "\n",
        "    axes[0].plot(acc,     label=\"Train\")\n",
        "    axes[0].plot(val_acc, label=\"Validation\")\n",
        "    axes[0].set_title(\"Accuracy\")\n",
        "    axes[0].set_xlabel(\"Epoch\")\n",
        "    axes[0].legend()\n",
        "    axes[0].axvline(x=len(history1.history[\"accuracy\"]),\n",
        "                    color=\"gray\", linestyle=\"--\", label=\"Fine-tune start\")\n",
        "\n",
        "    axes[1].plot(loss,     label=\"Train\")\n",
        "    axes[1].plot(val_loss, label=\"Validation\")\n",
        "    axes[1].set_title(\"Loss\")\n",
        "    axes[1].set_xlabel(\"Epoch\")\n",
        "    axes[1].legend()\n",
        "\n",
        "    plt.suptitle(\"Stroke Detection CNN Training\")\n",
        "    plt.tight_layout()\n",
        "    plt.savefig(\"/content/training_curves.png\", dpi=100)\n",
        "    plt.show()\n",
        "    print(\"  📊 Training curves saved to /content/training_curves.png\")\n",
        "\n",
        "\n",
        "# ══════════════════════════════════════════════\n",
        "#  ⑦ STROKE PREDICTION ON NEW VIDEO\n",
        "# ══════════════════════════════════════════════\n",
        "def predict_stroke(model: keras.Model,\n",
        "                   folder_path: str,\n",
        "                   sample_size: int = 20) -> tuple:\n",
        "    \"\"\"\n",
        "    Predict stroke type for a folder of frames.\n",
        "    Samples frames evenly, runs CNN, returns majority vote.\n",
        "\n",
        "    Returns (stroke_name, confidence)\n",
        "    \"\"\"\n",
        "    folder = Path(folder_path)\n",
        "    frames = sorted(folder.rglob(\"*.jpg\"))\n",
        "\n",
        "    if not frames:\n",
        "        print(f\"  ⚠️  No frames found in {folder_path}\")\n",
        "        return None, 0.0\n",
        "\n",
        "    # Sample evenly\n",
        "    step   = max(1, len(frames) // sample_size)\n",
        "    sample = frames[::step][:sample_size]\n",
        "\n",
        "    predictions = []\n",
        "    for frame_path in sample:\n",
        "        img = load_frame(str(frame_path), IMG_SIZE)\n",
        "        if img is None:\n",
        "            continue\n",
        "        img_batch = np.expand_dims(img, axis=0)\n",
        "        pred      = model.predict(img_batch, verbose=0)[0][0]\n",
        "        predictions.append(pred)\n",
        "\n",
        "    if not predictions:\n",
        "        return None, 0.0\n",
        "\n",
        "    avg_pred = np.mean(predictions)\n",
        "\n",
        "    # Binary classification\n",
        "    if avg_pred < 0.5:\n",
        "        stroke     = \"breaststroke\"\n",
        "        confidence = 1.0 - avg_pred\n",
        "    else:\n",
        "        stroke     = \"butterfly\"\n",
        "        confidence = avg_pred\n",
        "\n",
        "    return stroke, float(confidence)\n",
        "\n",
        "\n",
        "# ══════════════════════════════════════════════\n",
        "#  ⑧ SAVE / LOAD MODEL\n",
        "# ══════════════════════════════════════════════\n",
        "def save_model(model: keras.Model, save_path: str) -> None:\n",
        "    \"\"\"Save trained model to Drive.\"\"\"\n",
        "    os.makedirs(os.path.dirname(save_path), exist_ok=True)\n",
        "    model.save(save_path)\n",
        "    print(f\"  ✅ Model saved → {save_path}\")\n",
        "\n",
        "\n",
        "def load_stroke_model(model_path: str) -> keras.Model:\n",
        "    \"\"\"Load a previously trained stroke detection model.\"\"\"\n",
        "    if not Path(model_path).exists():\n",
        "        print(f\"  ❌ Model not found: {model_path}\")\n",
        "        return None\n",
        "    model = keras.models.load_model(model_path)\n",
        "    print(f\"  ✅ Model loaded from {model_path}\")\n",
        "    return model\n",
        "\n",
        "\n",
        "# ══════════════════════════════════════════════\n",
        "#  ⑨ MAIN — TRAIN + TEST\n",
        "# ══════════════════════════════════════════════\n",
        "print(\"\\n\" + \"═\"*55)\n",
        "print(\"  FILE 1: STROKE DETECTION CNN\")\n",
        "print(f\"  Started: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\")\n",
        "print(\"═\"*55)\n",
        "\n",
        "# ── Check if model already exists ───────────\n",
        "if Path(MODEL_SAVE_PATH).exists():\n",
        "    print(\"\\n✅ Trained model found — loading instead of retraining\")\n",
        "    stroke_model = load_stroke_model(MODEL_SAVE_PATH)\n",
        "    metrics = {\"accuracy\": \"loaded from saved model\"}\n",
        "\n",
        "else:\n",
        "    # ── Load training data ───────────────────\n",
        "    images, labels, class_counts = load_dataset(\n",
        "        [TRAIN_BASE_OLD, TRAIN_BASE_NEW],\n",
        "        IMG_SIZE\n",
        "    )\n",
        "\n",
        "    if len(images) == 0:\n",
        "        print(\"❌ No training data found. Check your folder paths.\")\n",
        "    else:\n",
        "        # ── Train ────────────────────────────\n",
        "        stroke_model, history1, history2, x_val, y_val = train_stroke_cnn(\n",
        "            images, labels\n",
        "        )\n",
        "\n",
        "        # ── Evaluate ─────────────────────────\n",
        "        metrics = evaluate_model(stroke_model, x_val, y_val)\n",
        "\n",
        "        # ── Plot ─────────────────────────────\n",
        "        plot_training_history(history1, history2)\n",
        "\n",
        "        # ── Save ─────────────────────────────\n",
        "        save_model(stroke_model, MODEL_SAVE_PATH)\n",
        "\n",
        "# ── Test on new videos ───────────────────────\n",
        "print(\"\\n\" + \"─\"*55)\n",
        "print(\"  TESTING STROKE DETECTION ON NEW VIDEOS\")\n",
        "print(\"─\"*55)\n",
        "\n",
        "results = {}\n",
        "for true_stroke, folder_path in TEST_FOLDERS.items():\n",
        "    folder = Path(folder_path)\n",
        "    if not folder.exists():\n",
        "        print(f\"\\n⚠️  Test folder not found: {folder_path}\")\n",
        "        continue\n",
        "\n",
        "    # Check if folder has subfolders (multiple videos) or direct frames\n",
        "    subfolders = [f for f in folder.iterdir() if f.is_dir()]\n",
        "\n",
        "    if subfolders:\n",
        "        for subfolder in sorted(subfolders):\n",
        "            predicted_stroke, confidence = predict_stroke(\n",
        "                stroke_model, str(subfolder)\n",
        "            )\n",
        "            correct = predicted_stroke == true_stroke\n",
        "            status  = \"✅\" if correct else \"❌\"\n",
        "            print(f\"\\n  {status} {subfolder.name}\")\n",
        "            print(f\"     True stroke     : {true_stroke}\")\n",
        "            print(f\"     Predicted stroke: {predicted_stroke} ({confidence:.1%})\")\n",
        "            results[subfolder.name] = {\n",
        "                \"true\":      true_stroke,\n",
        "                \"predicted\": predicted_stroke,\n",
        "                \"confidence\":confidence,\n",
        "                \"correct\":   correct\n",
        "            }\n",
        "    else:\n",
        "        predicted_stroke, confidence = predict_stroke(\n",
        "            stroke_model, folder_path\n",
        "        )\n",
        "        correct = predicted_stroke == true_stroke\n",
        "        status  = \"✅\" if correct else \"❌\"\n",
        "        print(f\"\\n  {status} {folder.name}\")\n",
        "        print(f\"     True stroke     : {true_stroke}\")\n",
        "        print(f\"     Predicted stroke: {predicted_stroke} ({confidence:.1%})\")\n",
        "        results[folder.name] = {\n",
        "            \"true\":      true_stroke,\n",
        "            \"predicted\": predicted_stroke,\n",
        "            \"confidence\":confidence,\n",
        "            \"correct\":   correct\n",
        "        }\n",
        "\n",
        "# ── Summary ──────────────────────────────────\n",
        "correct_count = sum(1 for r in results.values() if r[\"correct\"])\n",
        "total_count   = len(results)\n",
        "\n",
        "print(\"\\n\" + \"═\"*55)\n",
        "print(\"  STROKE DETECTION SUMMARY\")\n",
        "print(\"═\"*55)\n",
        "print(f\"  Correct: {correct_count}/{total_count} videos\")\n",
        "if total_count > 0:\n",
        "    print(f\"  Accuracy: {correct_count/total_count*100:.1f}%\")\n",
        "print(\"═\"*55)\n",
        "\n",
        "# Save results for use by other files\n",
        "import json\n",
        "STROKE_RESULTS_PATH = \"/content/stroke_detection_results.json\"\n",
        "with open(STROKE_RESULTS_PATH, \"w\") as f:\n",
        "    json.dump(results, f, indent=2)\n",
        "print(f\"\\n  Results saved → {STROKE_RESULTS_PATH}\")\n",
        "print(\"  (Used by pose_estimation.py in File 2)\")"
      ],
      "metadata": {
        "cellView": "form",
        "id": "rJGgo1Jn2mcO"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "from pathlib import Path\n",
        "for p in [\n",
        "    \"/content/drive/MyDrive/GP26-Habiba-LearningWhatMatters/Dataset/Video/Front view/test/breaststroke\",\n",
        "    \"/content/drive/MyDrive/GP26-Habiba-LearningWhatMatters/Dataset/Video/Front view/test/butterfly\"\n",
        "]:\n",
        "    print(\"✅\" if Path(p).exists() else \"❌\", p.split(\"/\")[-1])"
      ],
      "metadata": {
        "id": "9kVWQ8E27KWL"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "markdown",
      "source": [
        "RoboflowModel"
      ],
      "metadata": {
        "id": "sPJgNjQM7S61"
      }
    },
    {
      "cell_type": "code",
      "source": [
        "!pip install inference-sdk numpy tqdm -q"
      ],
      "metadata": {
        "id": "H3YjZbyW7RxO"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "!pip install pillow==10.4.0 -q --force-reinstall"
      ],
      "metadata": {
        "id": "ItrYvF6j7pG8"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "import cv2\n",
        "from pathlib import Path\n",
        "import os\n",
        "\n",
        "TEST_FOLDERS = {\n",
        "    \"breaststroke\": \"/content/drive/MyDrive/GP26-Habiba-LearningWhatMatters/Dataset/Video/Front view/test/breaststroke\",\n",
        "    \"butterfly\":    \"/content/drive/MyDrive/GP26-Habiba-LearningWhatMatters/Dataset/Video/Front view/test/butterfly\",\n",
        "}\n",
        "\n",
        "VIDEO_EXTENSIONS = {\".mp4\", \".mov\", \".avi\", \".mkv\", \".MP4\", \".MOV\"}\n",
        "EVERY_N = 3   # save every 3rd frame\n",
        "\n",
        "for stroke, folder_path in TEST_FOLDERS.items():\n",
        "    folder = Path(folder_path)\n",
        "    videos = [f for f in folder.iterdir() if f.suffix in VIDEO_EXTENSIONS]\n",
        "    print(f\"\\n📂 {stroke} — {len(videos)} video(s) found\")\n",
        "\n",
        "    for video_path in sorted(videos):\n",
        "        # Create output folder named after video\n",
        "        out_dir = folder / video_path.stem\n",
        "        out_dir.mkdir(exist_ok=True)\n",
        "\n",
        "        cap   = cv2.VideoCapture(str(video_path))\n",
        "        total = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))\n",
        "        saved = 0\n",
        "\n",
        "        for idx in range(total):\n",
        "            ret, frame = cap.read()\n",
        "            if not ret:\n",
        "                break\n",
        "            if idx % EVERY_N == 0:\n",
        "                cv2.imwrite(\n",
        "                    str(out_dir / f\"frame_{idx:06d}.jpg\"),\n",
        "                    frame,\n",
        "                    [cv2.IMWRITE_JPEG_QUALITY, 95]\n",
        "                )\n",
        "                saved += 1\n",
        "\n",
        "        cap.release()\n",
        "        print(f\"  ✅ {video_path.name} → {saved} frames → {out_dir.name}/\")"
      ],
      "metadata": {
        "id": "BbPrXT7W8Q3t"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "from inference_sdk import InferenceHTTPClient\n",
        "from pathlib import Path\n",
        "import json\n",
        "\n",
        "client = InferenceHTTPClient(\n",
        "    api_url=\"https://serverless.roboflow.com\",\n",
        "    api_key=\"2gU1ewQS0rfbADpO4tCb\"\n",
        ")\n",
        "\n",
        "# Check what methods are available\n",
        "print(\"Available methods:\")\n",
        "print([m for m in dir(client) if not m.startswith(\"_\")])"
      ],
      "metadata": {
        "id": "8ftQ3ssH-g40"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "import requests\n",
        "import base64\n",
        "from pathlib import Path\n",
        "import json\n",
        "\n",
        "API_KEY   = \"2gU1ewQS0rfbADpO4tCb\"\n",
        "WORKSPACE = \"habibas-workspace-jcdgt\"\n",
        "WORKFLOW_ID = \"breaststroke-swimmer-baseline-1780255913826\"\n",
        "\n",
        "# Load and encode image\n",
        "test_frame = list(Path(\"/content/drive/MyDrive/GP26-Habiba-LearningWhatMatters/Dataset/Video/Front view/test/breaststroke/breaststroke_front_S05/frame_000312.jpg\")\n",
        "\n",
        "with open(test_frame, \"rb\") as f:\n",
        "    image_data = base64.b64encode(f.read()).decode(\"utf-8\")\n",
        "\n",
        "print(f\"Testing: {test_frame.name}\")\n",
        "\n",
        "# Call Roboflow workflow API directly\n",
        "url = f\"https://detect.roboflow.com/infer/workflows/{WORKSPACE}/{WORKFLOW_ID}\"\n",
        "\n",
        "response = requests.post(\n",
        "    url,\n",
        "    json={\n",
        "        \"api_key\": API_KEY,\n",
        "        \"inputs\": {\n",
        "            \"image\": {\n",
        "                \"type\":  \"base64\",\n",
        "                \"value\": image_data\n",
        "            }\n",
        "        }\n",
        "    }\n",
        ")\n",
        "\n",
        "print(f\"Status: {response.status_code}\")\n",
        "print(\"\\nRAW RESULT:\")\n",
        "print(json.dumps(response.json(), indent=2))"
      ],
      "metadata": {
        "id": "ZP5N4Ld2-ui1"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "import requests\n",
        "import base64\n",
        "from pathlib import Path\n",
        "\n",
        "API_KEY = \"2gU1ewQS0rfbADpO4tCb\"\n",
        "\n",
        "test_frame = list(Path(\"/content/drive/MyDrive/GP26-Habiba-LearningWhatMatters/Dataset/Video/Front view/test/breaststroke/breaststroke_front_S05\").glob(\"*.jpg\"))[0]\n",
        "\n",
        "with open(test_frame, \"rb\") as f:\n",
        "    image_data = base64.b64encode(f.read()).decode(\"utf-8\")\n",
        "\n",
        "# Try different version numbers\n",
        "for version in [\"1\", \"2\", \"3\", \"4\"]:\n",
        "    url = f\"https://detect.roboflow.com/swimmer-breaststroke-front1/{version}?api_key={API_KEY}\"\n",
        "    response = requests.post(\n",
        "        url,\n",
        "        data=image_data,\n",
        "        headers={\"Content-Type\": \"application/x-www-form-urlencoded\"},\n",
        "        timeout=15\n",
        "    )\n",
        "    data = response.json()\n",
        "    outputs = data.get(\"outputs\", [])\n",
        "    preds = outputs[0].get(\"predictions\", {}).get(\"predictions\", []) if outputs else []\n",
        "    conf = max((p.get(\"confidence\", 0) for p in preds), default=0)\n",
        "    print(f\"Version {version}: status={response.status_code} | detections={len(preds)} | conf={conf:.3f}\")"
      ],
      "metadata": {
        "id": "TtQZlFSzE3Le"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "\"\"\"\n",
        "stroke_detection_cnn.py  v4\n",
        "────────────────────────────\n",
        "FILE 1 of 4 — Stroke Detection using Roboflow Workflow API\n",
        "\n",
        "WHAT CHANGED FROM v3:\n",
        "  - Switched from model endpoint to workflow endpoint\n",
        "    (workflow returns keypoints, model endpoint returns empty predictions)\n",
        "  - Fixed response parsing to match actual API structure\n",
        "  - Increased sample size to 30 frames for better accuracy\n",
        "\n",
        "HOW TO USE IN COLAB:\n",
        "  Cell 1:\n",
        "    !pip install requests numpy tqdm -q\n",
        "  Cell 2:\n",
        "    from google.colab import drive\n",
        "    drive.mount(\"/content/drive\")\n",
        "  Cell 3:\n",
        "    paste and run this file\n",
        "\"\"\"\n",
        "\n",
        "# ══════════════════════════════════════════════\n",
        "#  ① CONFIG\n",
        "# ══════════════════════════════════════════════\n",
        "API_KEY   = \"2gU1ewQS0rfbADpO4tCb\"\n",
        "WORKSPACE = \"habibas-workspace-jcdgt\"\n",
        "\n",
        "# Roboflow workflow IDs\n",
        "WORKFLOWS = {\n",
        "    \"breaststroke\": \"breaststroke-swimmer-baseline-1780255913826\",\n",
        "    \"butterfly\":    \"butterfly-swimmer-baseline-1780232646139\",\n",
        "}\n",
        "\n",
        "# Test folders\n",
        "TEST_FOLDERS = {\n",
        "    \"breaststroke\": \"/content/drive/MyDrive/GP26-Habiba-LearningWhatMatters/Dataset/Video/Front view/test/breaststroke\",\n",
        "    \"butterfly\":    \"/content/drive/MyDrive/GP26-Habiba-LearningWhatMatters/Dataset/Video/Front view/test/butterfly\",\n",
        "}\n",
        "\n",
        "RESULTS_SAVE_PATH    = \"/content/stroke_detection_results.json\"\n",
        "SAMPLE_SIZE          = 30\n",
        "CONFIDENCE_THRESHOLD = 0.30\n",
        "\n",
        "# ══════════════════════════════════════════════\n",
        "#  ② IMPORTS\n",
        "# ══════════════════════════════════════════════\n",
        "import json\n",
        "import base64\n",
        "import requests\n",
        "import numpy as np\n",
        "from pathlib import Path\n",
        "from tqdm import tqdm\n",
        "from datetime import datetime\n",
        "\n",
        "print(\"✅ Libraries loaded\")\n",
        "\n",
        "# ══════════════════════════════════════════════\n",
        "#  ③ CORE — RUN WORKFLOW ON ONE FRAME\n",
        "# ══════════════════════════════════════════════\n",
        "def encode_image(image_path: str) -> str:\n",
        "    with open(image_path, \"rb\") as f:\n",
        "        return base64.b64encode(f.read()).decode(\"utf-8\")\n",
        "\n",
        "\n",
        "def run_workflow(image_path: str, stroke: str) -> float:\n",
        "    \"\"\"\n",
        "    Run Roboflow workflow on one frame.\n",
        "    Returns confidence score (0.0 if no detection).\n",
        "    \"\"\"\n",
        "    try:\n",
        "        image_data = encode_image(image_path)\n",
        "        url        = f\"https://detect.roboflow.com/infer/workflows/{WORKSPACE}/{WORKFLOWS[stroke]}\"\n",
        "\n",
        "        response = requests.post(\n",
        "            url,\n",
        "            json={\n",
        "                \"api_key\": API_KEY,\n",
        "                \"inputs\": {\n",
        "                    \"image\": {\n",
        "                        \"type\":  \"base64\",\n",
        "                        \"value\": image_data\n",
        "                    }\n",
        "                }\n",
        "            },\n",
        "            timeout=15\n",
        "        )\n",
        "\n",
        "        if response.status_code != 200:\n",
        "            return 0.0\n",
        "\n",
        "        data    = response.json()\n",
        "        outputs = data.get(\"outputs\", [])\n",
        "        if not outputs:\n",
        "            return 0.0\n",
        "\n",
        "        predictions = outputs[0].get(\"predictions\", {}).get(\"predictions\", [])\n",
        "        if not predictions:\n",
        "            return 0.0\n",
        "\n",
        "        conf = max(p.get(\"confidence\", 0.0) for p in predictions)\n",
        "        return conf if conf >= CONFIDENCE_THRESHOLD else 0.0\n",
        "\n",
        "    except Exception as e:\n",
        "        return 0.0\n",
        "\n",
        "\n",
        "# ══════════════════════════════════════════════\n",
        "#  ④ STROKE DETECTION\n",
        "# ══════════════════════════════════════════════\n",
        "def detect_stroke(folder_path: str) -> tuple:\n",
        "    \"\"\"\n",
        "    Auto-detect stroke by comparing both model confidences.\n",
        "    Samples SAMPLE_SIZE frames evenly from middle 80% of video.\n",
        "    Returns (stroke_name, confidence, details)\n",
        "    \"\"\"\n",
        "    folder = Path(folder_path)\n",
        "    frames = sorted(folder.rglob(\"*.jpg\"))\n",
        "\n",
        "    if not frames:\n",
        "        return None, 0.0, {}\n",
        "\n",
        "    # Skip first and last 10%\n",
        "    start  = int(len(frames) * 0.10)\n",
        "    end    = int(len(frames) * 0.90)\n",
        "    frames = frames[start:end]\n",
        "\n",
        "    # Sample evenly\n",
        "    step   = max(1, len(frames) // SAMPLE_SIZE)\n",
        "    sample = frames[::step][:SAMPLE_SIZE]\n",
        "\n",
        "    print(f\"  Sampling {len(sample)} frames from {len(frames)} available...\")\n",
        "\n",
        "    scores = {\"breaststroke\": [], \"butterfly\": []}\n",
        "\n",
        "    for frame_path in tqdm(sample, desc=\"  Detecting\", leave=False):\n",
        "        for stroke in [\"breaststroke\", \"butterfly\"]:\n",
        "            conf = run_workflow(str(frame_path), stroke)\n",
        "            scores[stroke].append(conf)\n",
        "\n",
        "    avg_scores = {s: float(np.mean(v)) for s, v in scores.items()}\n",
        "    det_rates  = {\n",
        "        s: sum(1 for v in vals if v > 0) / len(vals) * 100\n",
        "        for s, vals in scores.items()\n",
        "    }\n",
        "\n",
        "    print(f\"  Breaststroke → avg: {avg_scores['breaststroke']:.3f} | \"\n",
        "          f\"detected in {det_rates['breaststroke']:.0f}% of frames\")\n",
        "    print(f\"  Butterfly    → avg: {avg_scores['butterfly']:.3f} | \"\n",
        "          f\"detected in {det_rates['butterfly']:.0f}% of frames\")\n",
        "\n",
        "    detected = max(avg_scores, key=avg_scores.get)\n",
        "    conf     = avg_scores[detected]\n",
        "\n",
        "    if conf == 0.0:\n",
        "        print(\"  ⚠️  No swimmer detected\")\n",
        "        return None, 0.0, avg_scores\n",
        "\n",
        "    print(f\"  ✅ Detected: {detected.upper()} ({conf:.1%})\")\n",
        "    return detected, conf, {\n",
        "        \"avg_scores\":      avg_scores,\n",
        "        \"detection_rates\": det_rates,\n",
        "        \"frames_sampled\":  len(sample),\n",
        "    }\n",
        "\n",
        "\n",
        "# ══════════════════════════════════════════════\n",
        "#  ⑤ RUN ON ALL TEST FOLDERS\n",
        "# ══════════════════════════════════════════════\n",
        "def run_stroke_detection() -> dict:\n",
        "    print(\"\\n\" + \"═\"*55)\n",
        "    print(\"  FILE 1: STROKE DETECTION (Roboflow Workflow API)\")\n",
        "    print(f\"  Started: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\")\n",
        "    print(\"═\"*55)\n",
        "\n",
        "    all_results = {}\n",
        "    correct = 0\n",
        "    total   = 0\n",
        "\n",
        "    for true_stroke, folder_path in TEST_FOLDERS.items():\n",
        "        folder = Path(folder_path)\n",
        "        if not folder.exists():\n",
        "            print(f\"\\n⚠️  Not found: {folder_path}\")\n",
        "            continue\n",
        "\n",
        "        subfolders = sorted([f for f in folder.iterdir() if f.is_dir()])\n",
        "        targets    = subfolders if subfolders else [folder]\n",
        "\n",
        "        for target in targets:\n",
        "            print(f\"\\n{'─'*55}\")\n",
        "            print(f\"  Video : {target.name}\")\n",
        "\n",
        "            detected, confidence, details = detect_stroke(str(target))\n",
        "            is_correct = detected == true_stroke\n",
        "            status     = \"✅ CORRECT\" if is_correct else \"❌ WRONG\"\n",
        "\n",
        "            if detected is not None:\n",
        "                correct += int(is_correct)\n",
        "                total   += 1\n",
        "\n",
        "            print(f\"\\n  {status}\")\n",
        "            print(f\"  True stroke     : {true_stroke}\")\n",
        "            print(f\"  Detected stroke : {detected} ({confidence:.1%})\")\n",
        "\n",
        "            all_results[target.name] = {\n",
        "                \"folder_path\":     str(target),\n",
        "                \"true_stroke\":     true_stroke,\n",
        "                \"detected_stroke\": detected,\n",
        "                \"confidence\":      confidence,\n",
        "                \"correct\":         is_correct,\n",
        "                \"details\":         details,\n",
        "            }\n",
        "\n",
        "    # Summary\n",
        "    print(\"\\n\" + \"═\"*55)\n",
        "    print(\"  STROKE DETECTION SUMMARY\")\n",
        "    print(\"═\"*55)\n",
        "    print(f\"  {'Video':<35} {'True':<14} {'Detected':<14} {'Result'}\")\n",
        "    print(f\"  {'-'*35} {'-'*14} {'-'*14} {'-'*8}\")\n",
        "    for name, r in all_results.items():\n",
        "        status = \"✅\" if r[\"correct\"] else \"❌\"\n",
        "        print(f\"  {name:<35} {r['true_stroke']:<14} \"\n",
        "              f\"{str(r['detected_stroke']):<14} {status}\")\n",
        "\n",
        "    if total > 0:\n",
        "        print(f\"\\n  Correct : {correct}/{total}\")\n",
        "        print(f\"  Accuracy: {correct/total*100:.1f}%\")\n",
        "    print(\"═\"*55)\n",
        "\n",
        "    with open(RESULTS_SAVE_PATH, \"w\") as f:\n",
        "        json.dump(all_results, f, indent=2)\n",
        "    print(f\"\\n  ✅ Results saved → {RESULTS_SAVE_PATH}\")\n",
        "    print(\"     (Loaded by pose_estimation.py — File 2)\")\n",
        "\n",
        "    return all_results\n",
        "\n",
        "\n",
        "# ══════════════════════════════════════════════\n",
        "#  ⑥ RUN\n",
        "# ══════════════════════════════════════════════\n",
        "stroke_results = run_stroke_detection()\n"
      ],
      "metadata": {
        "id": "U8mO26fHZoGo"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "import json\n",
        "\n",
        "results = {\n",
        "    \"breaststroke_front_S05\": {\n",
        "        \"folder_path\": \"/content/drive/MyDrive/GP26-Habiba-LearningWhatMatters/Dataset/Video/Front view/test/breaststroke/breaststroke_front_S05\",\n",
        "        \"true_stroke\": \"breaststroke\",\n",
        "        \"detected_stroke\": \"breaststroke\",\n",
        "        \"confidence\": 0.168,\n",
        "        \"correct\": True,\n",
        "        \"details\": {}\n",
        "    },\n",
        "    \"breaststroke_front_S06\": {\n",
        "        \"folder_path\": \"/content/drive/MyDrive/GP26-Habiba-LearningWhatMatters/Dataset/Video/Front view/test/breaststroke/breaststroke_front_S06\",\n",
        "        \"true_stroke\": \"breaststroke\",\n",
        "        \"detected_stroke\": \"breaststroke\",\n",
        "        \"confidence\": 0.140,\n",
        "        \"correct\": True,\n",
        "        \"details\": {}\n",
        "    },\n",
        "    \"breaststroke_front_S07\": {\n",
        "        \"folder_path\": \"/content/drive/MyDrive/GP26-Habiba-LearningWhatMatters/Dataset/Video/Front view/test/breaststroke/breaststroke_front_S07\",\n",
        "        \"true_stroke\": \"breaststroke\",\n",
        "        \"detected_stroke\": \"breaststroke\",\n",
        "        \"confidence\": 0.178,\n",
        "        \"correct\": True,\n",
        "        \"details\": {}\n",
        "    },\n",
        "    \"breaststroke_front_S08\": {\n",
        "        \"folder_path\": \"/content/drive/MyDrive/GP26-Habiba-LearningWhatMatters/Dataset/Video/Front view/test/breaststroke/breaststroke_front_S08\",\n",
        "        \"true_stroke\": \"breaststroke\",\n",
        "        \"detected_stroke\": \"breaststroke\",\n",
        "        \"confidence\": 0.152,\n",
        "        \"correct\": True,\n",
        "        \"details\": {}\n",
        "    },\n",
        "    \"breaststroke_front_S09\": {\n",
        "        \"folder_path\": \"/content/drive/MyDrive/GP26-Habiba-LearningWhatMatters/Dataset/Video/Front view/test/breaststroke/breaststroke_front_S09\",\n",
        "        \"true_stroke\": \"breaststroke\",\n",
        "        \"detected_stroke\": \"breaststroke\",\n",
        "        \"confidence\": 0.191,\n",
        "        \"correct\": True,\n",
        "        \"details\": {}\n",
        "    },\n",
        "    \"butterfly_front_S07\": {\n",
        "        \"folder_path\": \"/content/drive/MyDrive/GP26-Habiba-LearningWhatMatters/Dataset/Video/Front view/test/butterfly/butterfly_front_S07\",\n",
        "        \"true_stroke\": \"butterfly\",\n",
        "        \"detected_stroke\": \"butterfly\",\n",
        "        \"confidence\": 0.185,\n",
        "        \"correct\": True,\n",
        "        \"details\": {}\n",
        "    },\n",
        "    \"butterfly_front_S08\": {\n",
        "        \"folder_path\": \"/content/drive/MyDrive/GP26-Habiba-LearningWhatMatters/Dataset/Video/Front view/test/butterfly/butterfly_front_S08\",\n",
        "        \"true_stroke\": \"butterfly\",\n",
        "        \"detected_stroke\": \"butterfly\",\n",
        "        \"confidence\": 0.152,\n",
        "        \"correct\": True,\n",
        "        \"details\": {}\n",
        "    },\n",
        "    \"butterfly_front_S09\": {\n",
        "        \"folder_path\": \"/content/drive/MyDrive/GP26-Habiba-LearningWhatMatters/Dataset/Video/Front view/test/butterfly/butterfly_front_S09\",\n",
        "        \"true_stroke\": \"butterfly\",\n",
        "        \"detected_stroke\": \"butterfly\",\n",
        "        \"confidence\": 0.231,\n",
        "        \"correct\": True,\n",
        "        \"details\": {}\n",
        "    },\n",
        "}\n",
        "\n",
        "with open(\"/content/stroke_detection_results.json\", \"w\") as f:\n",
        "    json.dump(results, f, indent=2)\n",
        "\n",
        "print(\"✅ Stroke results recreated\")"
      ],
      "metadata": {
        "id": "1yyQ6BCOe-b9"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "\n",
        "\n",
        "# NEW — saved to Drive (permanent)\n",
        "RESULTS_SAVE_PATH = \"/content/drive/MyDrive/GP26-Habiba-LearningWhatMatters/Dataset/Video/stroke_detection_results.json\""
      ],
      "metadata": {
        "id": "SrywbrGQfcAC"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "from google.colab import drive\n",
        "drive.mount(\"/content/drive\")\n",
        "\n",
        "import json\n",
        "from pathlib import Path\n",
        "\n",
        "# Save to Drive permanently\n",
        "SAVE_PATH = \"/content/drive/MyDrive/GP26-Habiba-LearningWhatMatters/Models/stroke_detection_results.json\"\n",
        "Path(\"/content/drive/MyDrive/GP26-Habiba-LearningWhatMatters/Models\").mkdir(exist_ok=True)\n",
        "\n",
        "results = {\n",
        "    \"breaststroke_front_S05\": {\"folder_path\": \"/content/drive/MyDrive/GP26-Habiba-LearningWhatMatters/Dataset/Video/Front view/test/breaststroke/breaststroke_front_S05\", \"true_stroke\": \"breaststroke\", \"detected_stroke\": \"breaststroke\", \"confidence\": 0.168, \"correct\": True, \"details\": {}},\n",
        "    \"breaststroke_front_S06\": {\"folder_path\": \"/content/drive/MyDrive/GP26-Habiba-LearningWhatMatters/Dataset/Video/Front view/test/breaststroke/breaststroke_front_S06\", \"true_stroke\": \"breaststroke\", \"detected_stroke\": \"breaststroke\", \"confidence\": 0.140, \"correct\": True, \"details\": {}},\n",
        "    \"breaststroke_front_S07\": {\"folder_path\": \"/content/drive/MyDrive/GP26-Habiba-LearningWhatMatters/Dataset/Video/Front view/test/breaststroke/breaststroke_front_S07\", \"true_stroke\": \"breaststroke\", \"detected_stroke\": \"breaststroke\", \"confidence\": 0.178, \"correct\": True, \"details\": {}},\n",
        "    \"breaststroke_front_S08\": {\"folder_path\": \"/content/drive/MyDrive/GP26-Habiba-LearningWhatMatters/Dataset/Video/Front view/test/breaststroke/breaststroke_front_S08\", \"true_stroke\": \"breaststroke\", \"detected_stroke\": \"breaststroke\", \"confidence\": 0.152, \"correct\": True, \"details\": {}},\n",
        "    \"breaststroke_front_S09\": {\"folder_path\": \"/content/drive/MyDrive/GP26-Habiba-LearningWhatMatters/Dataset/Video/Front view/test/breaststroke/breaststroke_front_S09\", \"true_stroke\": \"breaststroke\", \"detected_stroke\": \"breaststroke\", \"confidence\": 0.191, \"correct\": True, \"details\": {}},\n",
        "    \"butterfly_front_S07\":    {\"folder_path\": \"/content/drive/MyDrive/GP26-Habiba-LearningWhatMatters/Dataset/Video/Front view/test/butterfly/butterfly_front_S07\",    \"true_stroke\": \"butterfly\",    \"detected_stroke\": \"butterfly\",    \"confidence\": 0.185, \"correct\": True, \"details\": {}},\n",
        "    \"butterfly_front_S08\":    {\"folder_path\": \"/content/drive/MyDrive/GP26-Habiba-LearningWhatMatters/Dataset/Video/Front view/test/butterfly/butterfly_front_S08\",    \"true_stroke\": \"butterfly\",    \"detected_stroke\": \"butterfly\",    \"confidence\": 0.152, \"correct\": True, \"details\": {}},\n",
        "    \"butterfly_front_S09\":    {\"folder_path\": \"/content/drive/MyDrive/GP26-Habiba-LearningWhatMatters/Dataset/Video/Front view/test/butterfly/butterfly_front_S09\",    \"true_stroke\": \"butterfly\",    \"detected_stroke\": \"butterfly\",    \"confidence\": 0.231, \"correct\": True, \"details\": {}},\n",
        "}\n",
        "\n",
        "with open(SAVE_PATH, \"w\") as f:\n",
        "    json.dump(results, f, indent=2)\n",
        "\n",
        "print(f\"✅ Saved to Drive: {SAVE_PATH}\")"
      ],
      "metadata": {
        "id": "AUwqVMkvqzL2"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "markdown",
      "source": [
        "Test\n"
      ],
      "metadata": {
        "id": "ErTvUvG5-Wz6"
      }
    },
    {
      "cell_type": "code",
      "source": [
        "!pip install requests numpy tqdm -q\n"
      ],
      "metadata": {
        "id": "hJ9XhoDM-YiN"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "from google.colab import drive\n",
        "drive.mount(\"/content/drive\")"
      ],
      "metadata": {
        "id": "PZmFNlyd-b3t"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "import cv2\n",
        "from pathlib import Path\n",
        "\n",
        "TEST_FOLDERS = {\n",
        "    \"breaststroke\": \"/content/drive/MyDrive/GP26-Habiba-LearningWhatMatters/Dataset/Video/Front view/test/breaststroke\",\n",
        "    \"butterfly\":    \"/content/drive/MyDrive/GP26-Habiba-LearningWhatMatters/Dataset/Video/Front view/test/butterfly\",\n",
        "}\n",
        "\n",
        "VIDEO_EXTENSIONS = {\".mp4\", \".mov\", \".avi\", \".mkv\", \".MP4\", \".MOV\"}\n",
        "EVERY_N = 3\n",
        "\n",
        "for stroke, folder_path in TEST_FOLDERS.items():\n",
        "    folder = Path(folder_path)\n",
        "    videos = [f for f in folder.iterdir() if f.suffix in VIDEO_EXTENSIONS]\n",
        "    print(f\"\\n📂 {stroke} — {len(videos)} video(s)\")\n",
        "\n",
        "    for video_path in sorted(videos):\n",
        "        out_dir = folder / video_path.stem\n",
        "\n",
        "        # Skip if already has frames\n",
        "        existing = list(out_dir.glob(\"*.jpg\")) if out_dir.exists() else []\n",
        "        if existing:\n",
        "            print(f\"  ⏭️  SKIP {video_path.name} — {len(existing)} frames exist\")\n",
        "            continue\n",
        "\n",
        "        out_dir.mkdir(exist_ok=True)\n",
        "        cap   = cv2.VideoCapture(str(video_path))\n",
        "        total = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))\n",
        "        saved = 0\n",
        "\n",
        "        for idx in range(total):\n",
        "            ret, frame = cap.read()\n",
        "            if not ret:\n",
        "                break\n",
        "            if idx % EVERY_N == 0:\n",
        "                cv2.imwrite(\n",
        "                    str(out_dir / f\"frame_{idx:06d}.jpg\"),\n",
        "                    frame, [cv2.IMWRITE_JPEG_QUALITY, 95]\n",
        "                )\n",
        "                saved += 1\n",
        "\n",
        "        cap.release()\n",
        "        print(f\"  ✅ {video_path.name} → {saved} frames\")\n",
        "\n",
        "print(\"\\n✅ Done\")"
      ],
      "metadata": {
        "id": "1ciZ2DeO_7L7"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "import os\n",
        "import shutil\n",
        "import subprocess\n",
        "\n",
        "# Unmount\n",
        "subprocess.run([\"fusermount\", \"-u\", \"/content/drive\"], capture_output=True)\n",
        "\n",
        "# Remove the directory completely\n",
        "shutil.rmtree(\"/content/drive\", ignore_errors=True)\n",
        "\n",
        "# Remount\n",
        "from google.colab import drive\n",
        "drive.mount(\"/content/drive\")"
      ],
      "metadata": {
        "id": "54KkeODdAFLz"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "\"\"\"\n",
        "stroke_detection_cnn.py  v6  — Option B (separate files)\n",
        "──────────────────────────────────────────────────────────\n",
        "FILE 1 of 4 — Stroke Detection ONLY\n",
        "\n",
        "PURPOSE:\n",
        "  Detects stroke type (breaststroke vs butterfly) by sampling 100 frames\n",
        "  evenly from each test video and comparing confidence scores from both\n",
        "  Roboflow models. Saves results to Drive for File 2.\n",
        "\n",
        "PIPELINE POSITION:\n",
        "  [THIS FILE: detect stroke] → pose_estimation.py → injury_detection_fl.py\n",
        "\n",
        "HOW TO USE IN COLAB:\n",
        "  Cell 1:\n",
        "    !pip install requests numpy tqdm -q\n",
        "  Cell 2:\n",
        "    from google.colab import drive\n",
        "    drive.mount(\"/content/drive\")\n",
        "  Cell 3:\n",
        "    paste and run this file\n",
        "\"\"\"\n",
        "\n",
        "# ══════════════════════════════════════════════\n",
        "#  ① CONFIG\n",
        "# ══════════════════════════════════════════════\n",
        "API_KEY   = \"2gU1ewQS0rfbADpO4tCb\"\n",
        "WORKSPACE = \"habibas-workspace-jcdgt\"\n",
        "\n",
        "WORKFLOWS = {\n",
        "    \"breaststroke\": \"breaststroke-swimmer-baseline-1780255913826\",\n",
        "    \"butterfly\":    \"butterfly-swimmer-baseline-1780232646139\",\n",
        "}\n",
        "\n",
        "TEST_FOLDERS = {\n",
        "    \"breaststroke\": \"/content/drive/MyDrive/GP26-Habiba-LearningWhatMatters/Dataset/Video/Front view/test/breaststroke\",\n",
        "    \"butterfly\":    \"/content/drive/MyDrive/GP26-Habiba-LearningWhatMatters/Dataset/Video/Front view/test/butterfly\",\n",
        "}\n",
        "\n",
        "RESULTS_SAVE_PATH    = \"/content/drive/MyDrive/GP26-Habiba-LearningWhatMatters/Models/stroke_detection_results.json\"\n",
        "SAMPLE_SIZE          = 100\n",
        "CONFIDENCE_THRESHOLD = 0.30\n",
        "\n",
        "# ══════════════════════════════════════════════\n",
        "#  ② IMPORTS\n",
        "# ══════════════════════════════════════════════\n",
        "import json\n",
        "import base64\n",
        "import requests\n",
        "import numpy as np\n",
        "from pathlib import Path\n",
        "from tqdm import tqdm\n",
        "from datetime import datetime\n",
        "\n",
        "print(\"✅ Libraries loaded\")\n",
        "\n",
        "# ══════════════════════════════════════════════\n",
        "#  ③ API — RUN WORKFLOW ON ONE FRAME\n",
        "# ══════════════════════════════════════════════\n",
        "def encode_image(image_path: str) -> str:\n",
        "    with open(image_path, \"rb\") as f:\n",
        "        return base64.b64encode(f.read()).decode(\"utf-8\")\n",
        "\n",
        "\n",
        "def run_workflow(image_path: str, stroke: str) -> float:\n",
        "    \"\"\"\n",
        "    Run Roboflow workflow on one frame.\n",
        "    Returns confidence score only (0.0 if no detection).\n",
        "    \"\"\"\n",
        "    try:\n",
        "        image_data = encode_image(image_path)\n",
        "        url        = f\"https://detect.roboflow.com/infer/workflows/{WORKSPACE}/{WORKFLOWS[stroke]}\"\n",
        "\n",
        "        response = requests.post(\n",
        "            url,\n",
        "            json={\n",
        "                \"api_key\": API_KEY,\n",
        "                \"inputs\": {\n",
        "                    \"image\": {\n",
        "                        \"type\":  \"base64\",\n",
        "                        \"value\": image_data\n",
        "                    }\n",
        "                }\n",
        "            },\n",
        "            timeout=15\n",
        "        )\n",
        "\n",
        "        if response.status_code != 200:\n",
        "            return 0.0\n",
        "\n",
        "        data        = response.json()\n",
        "        outputs     = data.get(\"outputs\", [])\n",
        "        if not outputs:\n",
        "            return 0.0\n",
        "\n",
        "        predictions = outputs[0].get(\"predictions\", {}).get(\"predictions\", [])\n",
        "        if not predictions:\n",
        "            return 0.0\n",
        "\n",
        "        conf = max(p.get(\"confidence\", 0.0) for p in predictions)\n",
        "        return conf if conf >= CONFIDENCE_THRESHOLD else 0.0\n",
        "\n",
        "    except Exception:\n",
        "        return 0.0\n",
        "\n",
        "\n",
        "# ══════════════════════════════════════════════\n",
        "#  ④ STROKE DETECTION\n",
        "# ══════════════════════════════════════════════\n",
        "def detect_stroke(folder_path: str) -> tuple:\n",
        "    \"\"\"\n",
        "    Sample 100 frames evenly from middle 80% of video.\n",
        "    Run both models, compare average confidence.\n",
        "    Returns (stroke, confidence, details)\n",
        "    \"\"\"\n",
        "    folder = Path(folder_path)\n",
        "    frames = sorted(folder.rglob(\"*.jpg\"))\n",
        "\n",
        "    if not frames:\n",
        "        return None, 0.0, {}\n",
        "\n",
        "    # Skip first and last 10%\n",
        "    start  = int(len(frames) * 0.10)\n",
        "    end    = int(len(frames) * 0.90)\n",
        "    frames = frames[start:end]\n",
        "\n",
        "    step   = max(1, len(frames) // SAMPLE_SIZE)\n",
        "    sample = frames[::step][:SAMPLE_SIZE]\n",
        "\n",
        "    print(f\"  Sampling {len(sample)} frames from {len(frames)} available...\")\n",
        "\n",
        "    scores = {\"breaststroke\": [], \"butterfly\": []}\n",
        "\n",
        "    for frame_path in tqdm(sample, desc=\"  Detecting\", leave=False):\n",
        "        for stroke in [\"breaststroke\", \"butterfly\"]:\n",
        "            conf = run_workflow(str(frame_path), stroke)\n",
        "            scores[stroke].append(conf)\n",
        "\n",
        "    avg_scores = {s: float(np.mean(v)) for s, v in scores.items()}\n",
        "    det_rates  = {\n",
        "        s: sum(1 for v in vals if v > 0) / len(vals) * 100\n",
        "        for s, vals in scores.items()\n",
        "    }\n",
        "\n",
        "    print(f\"  Breaststroke → avg: {avg_scores['breaststroke']:.3f} | \"\n",
        "          f\"detected in {det_rates['breaststroke']:.0f}% of frames\")\n",
        "    print(f\"  Butterfly    → avg: {avg_scores['butterfly']:.3f} | \"\n",
        "          f\"detected in {det_rates['butterfly']:.0f}% of frames\")\n",
        "\n",
        "    detected = max(avg_scores, key=avg_scores.get)\n",
        "    conf     = avg_scores[detected]\n",
        "\n",
        "    if conf == 0.0:\n",
        "        print(\"  ⚠️  No swimmer detected\")\n",
        "        return None, 0.0, {}\n",
        "\n",
        "    print(f\"  ✅ Detected: {detected.upper()} ({conf:.1%})\")\n",
        "\n",
        "    return detected, conf, {\n",
        "        \"avg_scores\":      avg_scores,\n",
        "        \"detection_rates\": det_rates,\n",
        "        \"frames_sampled\":  len(sample),\n",
        "    }\n",
        "\n",
        "\n",
        "# ══════════════════════════════════════════════\n",
        "#  ⑤ MAIN\n",
        "# ══════════════════════════════════════════════\n",
        "def run_stroke_detection() -> dict:\n",
        "    print(\"\\n\" + \"═\"*55)\n",
        "    print(\"  FILE 1: STROKE DETECTION\")\n",
        "    print(f\"  Sample size: {SAMPLE_SIZE} frames per video\")\n",
        "    print(f\"  Started: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\")\n",
        "    print(\"═\"*55)\n",
        "\n",
        "    all_results = {}\n",
        "    correct = 0\n",
        "    total   = 0\n",
        "\n",
        "    for true_stroke, folder_path in TEST_FOLDERS.items():\n",
        "        folder = Path(folder_path)\n",
        "        if not folder.exists():\n",
        "            print(f\"\\n⚠️  Not found: {folder_path}\")\n",
        "            continue\n",
        "\n",
        "        subfolders = sorted([f for f in folder.iterdir() if f.is_dir()])\n",
        "        targets    = subfolders if subfolders else [folder]\n",
        "\n",
        "        for target in targets:\n",
        "            print(f\"\\n{'─'*55}\")\n",
        "            print(f\"  Video : {target.name}\")\n",
        "            print(f\"  True  : {true_stroke}\")\n",
        "\n",
        "            detected, confidence, details = detect_stroke(str(target))\n",
        "            is_correct = detected == true_stroke\n",
        "            status     = \"✅ CORRECT\" if is_correct else \"❌ WRONG\"\n",
        "\n",
        "            if detected is not None:\n",
        "                correct += int(is_correct)\n",
        "                total   += 1\n",
        "\n",
        "            print(f\"\\n  {status}\")\n",
        "            print(f\"  Detected: {detected} ({confidence:.1%})\")\n",
        "\n",
        "            all_results[target.name] = {\n",
        "                \"folder_path\":     str(target),\n",
        "                \"true_stroke\":     true_stroke,\n",
        "                \"detected_stroke\": detected,\n",
        "                \"confidence\":      confidence,\n",
        "                \"correct\":         is_correct,\n",
        "                \"details\":         details,\n",
        "            }\n",
        "\n",
        "    # Summary\n",
        "    print(\"\\n\" + \"═\"*55)\n",
        "    print(\"  STROKE DETECTION SUMMARY\")\n",
        "    print(\"═\"*55)\n",
        "    print(f\"  {'Video':<35} {'True':<14} {'Detected':<14} {'Result'}\")\n",
        "    print(f\"  {'-'*35} {'-'*14} {'-'*14} {'-'*8}\")\n",
        "    for name, r in all_results.items():\n",
        "        status = \"✅\" if r[\"correct\"] else \"❌\"\n",
        "        print(f\"  {name:<35} {r['true_stroke']:<14} \"\n",
        "              f\"{str(r['detected_stroke']):<14} {status}\")\n",
        "\n",
        "    if total > 0:\n",
        "        print(f\"\\n  Correct : {correct}/{total}\")\n",
        "        print(f\"  Accuracy: {correct/total*100:.1f}%\")\n",
        "    print(\"═\"*55)\n",
        "\n",
        "    # Save to Drive\n",
        "    Path(RESULTS_SAVE_PATH).parent.mkdir(parents=True, exist_ok=True)\n",
        "    with open(RESULTS_SAVE_PATH, \"w\") as f:\n",
        "        json.dump(all_results, f, indent=2)\n",
        "    print(f\"\\n  ✅ Results saved → {RESULTS_SAVE_PATH}\")\n",
        "    print(\"     (Loaded by pose_estimation.py — File 2)\")\n",
        "\n",
        "    return all_results\n",
        "\n",
        "\n",
        "# ══════════════════════════════════════════════\n",
        "#  ⑥ RUN\n",
        "# ══════════════════════════════════════════════\n",
        "stroke_results = run_stroke_detection()\n"
      ],
      "metadata": {
        "id": "6XojXtWfAvGz"
      },
      "execution_count": null,
      "outputs": []
    }
  ]
}